# Generated by Django 6.0.5 on 2026-06-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('jazzcash', 'JazzCash'), ('easypaisa', 'EasyPaisa'), ('raast', 'Raast Transfer'), ('bank', 'Bank Transfer'), ('cash', 'Cash on Delivery')], default='cash', max_length=20),
        ),
    ]
