# Generated by Django 6.0.5 on 2026-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_sizes',
            field=models.BooleanField(default=False, help_text='Enable size selection (S, M, L)'),
        ),
    ]
